export enum Category {
  ALIMENTATION = 'ALIMENTATION',
  MAINS = 'MAINS',
  CHEVEUX = 'CHEVEUX',
  VISAGE = 'VISAGE',
  CORPS = 'CORPS',
  PARFUMS = 'PARFUMS',
  CHATS = 'CHATS',
  CHIENS = 'CHIENS',
  CHAUDE = 'CHAUDE',
  FROIDE = 'FROIDE',
  SANS_ALCOOL = 'SANS_ALCOOL',
  AVEC_ALCOOL = 'AVEC_ALCOOL',
  MENAGE = 'MENAGE',
  CONFISERIES = 'CONFISERIES',
  APPAREILS = 'APPAREILS',
}


